#include <cassert>
#include <iostream>

#include "stellar_gpu_profile_contract_v053k.h"

int main()
{
  assert(stellarGpuProfileContractValidV053k(
      STELLAR_RENDER_PROGRAM_RETAINED_V078_V081,
      STELLAR_TRANSFER_COMPOSITE,
      STELLAR_PALETTE_COPPER_BLUE_ACCENT_V058,
      STELLAR_FEATURE_STRUCTURES_V065,
      STELLAR_PHYSICAL_OPTICAL_COMPOSITE_MOMENT_V078));
  assert(stellarGpuProfileContractValidV053k(
      STELLAR_RENDER_PROGRAM_HERO_ADAPTIVE_COPPER_BLUE_V081,
      STELLAR_TRANSFER_COMPOSITE,
      STELLAR_PALETTE_COPPER_BLUE_ACCENT_V058,
      STELLAR_FEATURE_STRUCTURES_V065,
      STELLAR_PHYSICAL_OPTICAL_LEGACY_V072));
  assert(!stellarGpuProfileContractValidV053k(
      STELLAR_RENDER_PROGRAM_HERO_ADAPTIVE_COPPER_BLUE_V081,
      STELLAR_TRANSFER_DISK,
      STELLAR_PALETTE_COPPER_BLUE_ACCENT_V058,
      STELLAR_FEATURE_STRUCTURES_V065,
      STELLAR_PHYSICAL_OPTICAL_LEGACY_V072));
  assert(!stellarGpuProfileContractValidV053k(
      STELLAR_RENDER_PROGRAM_HERO_ADAPTIVE_COPPER_BLUE_V081,
      STELLAR_TRANSFER_COMPOSITE,
      STELLAR_PALETTE_STRUCTURE_FLUX_VIVID_V068,
      STELLAR_FEATURE_STRUCTURES_V065,
      STELLAR_PHYSICAL_OPTICAL_LEGACY_V072));
  std::cout << "STELLAR_GPU_PHYSICAL_CONTRACT_V053K_OK "
            << "retained=v053h hero=hero_adaptive_copper_blue_v081\n";
  return 0;
}
